name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: main.pdf
          repo-token: ${{ secrets.GITHUB_TOKEN }}
